"""
  =====================================================
  cities.py — City List API Route
  =====================================================
  This simple endpoint returns a list of all cities
  that have listings, along with how many listings
  each city has.

  It uses SQL GROUP BY and COUNT — the database does
  the counting, not Python. This is far more efficient
  than fetching all listings and counting in Python.

  SQL QUERY GENERATED BY SQLAlchemy:
    SELECT city, COUNT(id) AS count
    FROM listings
    GROUP BY city
    ORDER BY count DESC

  This returns rows like:
    ("Nairobi", 3), ("Embu", 3), ("Kisumu", 2), ...
"""

from fastapi import APIRouter, Depends
from sqlalchemy import select, func
from sqlalchemy.ext.asyncio import AsyncSession

from backend.database import get_db
from backend.models import Listing
from backend.schemas import CityInfo

# Mount at /api/cities so all routes start with that prefix
router = APIRouter(prefix="/api/cities", tags=["cities"])


@router.get("", response_model=list[CityInfo])
async def list_cities(
    db: AsyncSession = Depends(get_db),
):
    """
    GET /api/cities
    Returns all cities that have listings, with counts,
    ordered by most listings first.

    SQLAlchemy's func.count() generates the SQL COUNT()
    aggregate function. .label("count") gives the result
    column a name we can reference.

    The return statement converts each raw database row
    to a CityInfo Pydantic schema (name + count).
    """
    # Build query: select city and count of listings per city
    stmt = (
        select(Listing.city, func.count(Listing.id).label("count"))
        .group_by(Listing.city)           # Group rows by city
        .order_by(func.count(Listing.id).desc())  # Most listings first
    )

    # Execute the query
    result = await db.execute(stmt)
    rows = result.all()  # Returns a list of Row objects

    # Convert Row objects to Pydantic CityInfo schemas
    return [CityInfo(name=row[0], count=row[1]) for row in rows]
